A small CLI application to display provided help scripts
uyuni-project/hub-xmlrpc-api pull request #15
Opened 2020-03-20 17:05 UTC by admd

2020-03-20 21:49 UTC, isbm requested changes

2020-03-20 21:49 UTC, isbm commented on example_scripts/main.go
> +						return nil
Uhmm.... Quite weird design. :wink:  No, you don't do that. You just put one flag, like "mode" and then one global action and simply pass context there. Then inside `readExampleContents` you get it like:

```go
switch c.String("mode"):
case "relay":
    ...
default:
    cli.ShowAppHelpAndExit(c, 1)
```

2020-03-20 21:51 UTC, isbm commented on example_scripts/main.go
> +						return nil
P.S. I think just a simple bash script is less overkill for this tho. :wink:

2020-03-30 10:34 UTC, admd commented
No need anymore. Closing it

2020-03-30 10:34 UTC, closed without merging